export type { MapView } from '$shared/geo';
export {
  type FloatingInstrumentBox,
  floatingInstrumentBoxesCodec,
  isFloatingInstrumentBox,
  isFloatingInstrumentBoxes,
  MAX_FLOATING_INSTRUMENTS,
  MIN_FLOATING_HEIGHT,
  MIN_FLOATING_WIDTH,
  sanitizeFloatingInstrumentBox,
} from './floating-instruments';
export {
  DEFAULT_MAP_RENDERING_QUALITY,
  MAP_RENDERING_QUALITIES,
  type MapRenderingQuality,
  mapRenderingPixelRatio,
} from './map-rendering-quality';
export type {
  AlarmLocation,
  ChartOrientationMode,
  PersistedCodec,
  PersistedDecodeResult,
  PersistedRepairStatus,
  PersistedValidator,
  StorageLike,
  Thresholds,
  TrackSettings,
} from './persisted.svelte';
export {
  ALARM_LOCATIONS,
  arrayPersistedCodec,
  booleanPersistedCodec,
  booleanRecordPersistedCodec,
  boundedNumberPersistedCodec,
  CHART_ORIENTATION_MODES,
  createAlarmLocation,
  createMapView,
  createPersistedCodec,
  createPlanningSpeed,
  createThresholds,
  createTrackSettings,
  DEFAULT_ALARM_LOCATION,
  DEFAULT_THRESHOLDS,
  DEFAULT_TRACK_STOP_DURATION_MINUTES,
  DEFAULT_TRACK_STOP_SPEED_KNOTS,
  enumPersistedCodec,
  exactShapeCodec,
  isMapView,
  isThresholds,
  isTrackSettings,
  MAX_COLLISION_CPA_METERS,
  MAX_COLLISION_TCPA_SECONDS,
  MAX_PLANNING_SPEED_KN,
  MAX_PLANNING_SPEED_MPS,
  MAX_SHALLOW_DEPTH_METERS,
  nullablePersistedCodec,
  PersistedValue,
  preferTrackHistory,
  stringArrayPersistedCodec,
  trackStopDurationMinutes,
  trackStopSpeedKnots,
  tripLogEnabled,
  useLocalTrackFallback,
} from './persisted.svelte';
export {
  isWeatherSourceId,
  WEATHER_SOURCE_OPTIONS,
  type WeatherSourceId,
  type WeatherSourceOption,
  weatherSourceOption,
} from './weather-source';
export {
  DEFAULT_WIND_ROSE_ARC_MARGIN_RAD,
  DEFAULT_WIND_ROSE_NO_GO_ANGLE_RAD,
  isWindRoseArcMarginRad,
  isWindRoseNoGoAngleRad,
  MAX_WIND_ROSE_ARC_MARGIN_RAD,
  MAX_WIND_ROSE_NO_GO_ANGLE_RAD,
  MIN_WIND_ROSE_ARC_MARGIN_RAD,
  MIN_WIND_ROSE_NO_GO_ANGLE_RAD,
} from './wind-rose';
